# Generated by Django 5.0.3 on 2024-03-07 09:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='lecture_notes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system.course')),
            ],
        ),
        migrations.CreateModel(
            name='PastPapers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='tutorials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])])),
                ('solution', models.FileField(blank=True, upload_to='solutions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])])),
                ('test_date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system.course')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='tutorials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system.course')),
            ],
        ),
    ]
