# Generated by Django 5.0.3 on 2024-03-07 12:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorials',
            new_name='Tutorial',
        ),
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='tutorials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])])),
                ('solution', models.FileField(blank=True, upload_to='solutions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system.course')),
            ],
        ),
        migrations.DeleteModel(
            name='PastPapers',
        ),
    ]
