# Generated by Django 5.0.3 on 2024-03-12 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0003_alter_lecture_id_alter_pastpaper_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='file',
            field=models.FileField(upload_to='past papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])]),
        ),
    ]
