# Generated by Django 5.0.3 on 2024-04-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0004_alter_pastpaper_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('degree_name', models.CharField(max_length=255)),
            ],
        ),
    ]
