# Generated by Django 5.0.3 on 2024-04-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0005_degreeprogram'),
        ('myusers', '0011_remove_user_degree_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DegreeProgram',
        ),
    ]
