# Generated by Django 5.0.3 on 2024-04-13 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0006_delete_degreeprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('degree_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='year_taught',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='degree_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='learning_system.degreeprogram'),
            preserve_default=False,
        ),
    ]
