# Generated by Django 5.0.3 on 2024-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0007_degreeprogram_course_year_taught_course_degree_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.TextField(default='nuh is awesome', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second')], default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='course',
            name='degree_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year_taught',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.AddField(
            model_name='course',
            name='degree_id',
            field=models.ManyToManyField(to='learning_system.degreeprogram'),
        ),
        migrations.AddField(
            model_name='course',
            name='year_taught',
            field=models.ManyToManyField(to='learning_system.year'),
        ),
    ]
