# Generated by Django 5.0.3 on 2024-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0008_year_course_notes_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year_taught',
            field=models.ManyToManyField(blank=True, null=True, to='learning_system.year'),
        ),
    ]
