# Generated by Django 4.0.10 on 2024-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0009_alter_course_year_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(verbose_name={1: 'first', 2: 'second'}),
        ),
        migrations.AlterField(
            model_name='course',
            name='year_taught',
            field=models.ManyToManyField(blank=True, to='learning_system.year'),
        ),
    ]
