# Generated by Django 4.2.7 on 2024-04-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0010_alter_course_semester_alter_course_year_taught'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
