# Generated by Django 4.2.7 on 2024-04-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0013_remove_course_semester_course_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='degree_id',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='pastpaper',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year_taught',
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second')]),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
