# Generated by Django 3.2.25 on 2024-05-10 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0016_auto_20240510_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='file',
            field=models.FileField(upload_to='past papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])]),
        ),
    ]
