# Generated by Django 5.0.3 on 2024-03-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
