# Generated by Django 5.0.3 on 2024-03-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='nuh', max_length=255),
            preserve_default=False,
        ),
    ]
