# Generated by Django 5.0.3 on 2024-03-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0004_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
