# Generated by Django 5.0.3 on 2024-03-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
