# Generated by Django 5.0.3 on 2024-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
