# Generated by Django 5.0.3 on 2024-04-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0010_user_degree_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='degree_program',
        ),
    ]
